name: Core
version: 1.0
api-version: 1.19
main: net.vertrauterdavid.Core
author: VertrauterDavid
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

softdepend: [PlaceholderAPI]

commands: